name: Build for dev
on:
    push:
        branches:
            - dev

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            deployments: write
            packages: write
            contents: read
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
              with:
                  install: true

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: ./Dockerfile
                  push: false

            - name: Clean up images
              run: docker system prune -f
